adicionar walisson
paft-inc/paft-microservices pull request #11
Opened 2022-12-01 23:40 UTC by Anexxed26

2022-12-01 23:40 UTC, tomtomdevops submitted a review, later dismissed
ok

2022-12-01 23:41 UTC, Botelhomf submitted a review, later dismissed

2022-12-01 23:42 UTC, rafaelrubira2 submitted a review, later dismissed

2022-12-01 23:45 UTC, renatodru approved these changes

2022-12-01 23:49 UTC, VictorFranca11 approved these changes

2022-12-02 00:34 UTC, rafaelrubira2 submitted a review, later dismissed

2022-12-02 00:37 UTC, tomtomdevops submitted a review, later dismissed

2022-12-02 00:51 UTC, renatodru approved these changes

2022-12-02 00:51 UTC, VictorFranca11 approved these changes

2022-12-02 00:52 UTC, Botelhomf requested changes
Atualize seu codigo

2022-12-02 00:55 UTC, rafaelrubira2 approved these changes

2022-12-02 00:56 UTC, rafaelrubira2 commented
> Atualize seu codigo

Ajustado!

2022-12-02 01:02 UTC, rafaelrubira2 approved these changes

2022-12-02 16:33 UTC, Lohann approved these changes

2022-12-02 16:45 UTC, closed without merging