renatodru adicionado
paft-inc/paft-microservices pull request #12
Opened 2022-12-01 23:40 UTC by renatodru

2022-12-01 23:41 UTC, Anexxed26 submitted a review, later dismissed

2022-12-01 23:42 UTC, rafaelrubira2 requested changes
Só o nome. Overkill!

2022-12-01 23:50 UTC, rafaelrubira2 submitted a review, later dismissed
BãoD+

2022-12-01 23:57 UTC, MateusCamillo approved these changes

2022-12-01 23:58 UTC, ManicaFelipe submitted a review, later dismissed

2022-12-02 00:25 UTC, JEFadel submitted a review, later dismissed

2022-12-02 16:45 UTC, closed without merging