Adicionado cmpiska ao Mantainers
paft-inc/paft-microservices pull request #19
Opened 2022-12-01 23:56 UTC by cmpiska

Adicionado cmpiska ao Mantainers

2022-12-01 23:58 UTC, Anexxed26 submitted a review, later dismissed

2022-12-01 23:58 UTC, JEFadel submitted a review, later dismissed

2022-12-02 00:00 UTC, rafaelrubira2 requested changes
Tem espaço no arquivo

2022-12-02 00:00 UTC, renatodru submitted a review, later dismissed

2022-12-02 00:02 UTC, ManicaFelipe approved these changes

2022-12-02 00:23 UTC, Rodrigojorge1 approved these changes

2022-12-02 00:28 UTC, Rodrigojorge1 approved these changes

2022-12-02 00:38 UTC, Botelhomf requested changes
Por favor adicione seu nome nao seu apelido!

2022-12-02 16:45 UTC, closed without merging