Adicionar Daniel ao mantainers
paft-inc/paft-microservices pull request #8
Opened 2022-12-01 23:38 UTC by Botelhomf

2022-12-01 23:39 UTC, rafaelrubira2 submitted a review, later dismissed
ok

2022-12-01 23:40 UTC, tomtomdevops submitted a review, later dismissed

2022-12-01 23:44 UTC, Lohann approved these changes

2022-12-01 23:44 UTC, renatodru submitted a review, later dismissed

2022-12-01 23:49 UTC, VictorFranca11 submitted a review, later dismissed

2022-12-01 23:59 UTC, Lohann requested changes

2022-12-01 23:59 UTC, Lohann commented on maintainers
> +
Remover espaços em branco

2022-12-02 00:02 UTC, rafaelrubira2 requested changes
Linhas em branco

2022-12-02 00:29 UTC, Lohann approved these changes

2022-12-02 00:43 UTC, Lohann approved these changes

2022-12-02 00:44 UTC, renatodru approved these changes

2022-12-02 00:44 UTC, ManicaFelipe approved these changes

2022-12-02 00:44 UTC, Anexxed26 approved these changes

2022-12-02 00:44 UTC, rafaelrubira2 approved these changes

2022-12-02 00:44 UTC, merged